// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBURurFn2MmTC7rsRxtlr7aWzofC_hOOBw',
    appId: '1:451988183629:android:12a5c54e058a708bc91a04',
    messagingSenderId: '451988183629',
    projectId: 'my-movie-app-2025',
    storageBucket: 'my-movie-app-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8YznKPrbM_ix60pvkRggaCVM92SPRqrw',
    appId: '1:451988183629:ios:5be79f8a808f076ec91a04',
    messagingSenderId: '451988183629',
    projectId: 'my-movie-app-2025',
    storageBucket: 'my-movie-app-2025.firebasestorage.app',
    androidClientId: '451988183629-1b04frs8ohutb0e1jjn7q03a6qf91apa.apps.googleusercontent.com',
    iosClientId: '451988183629-rck8p4qoe623scan04ngrd2th3c3t6h2.apps.googleusercontent.com',
    iosBundleId: 'com.example.moviesApp',
  );

}